<?php

namespace App\Models;

use App\Scopes\AdminScope;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Admin extends User
{
    use HasFactory;
   protected $table='users';
   protected static function boot()
   {
       parent::boot();
       // TODO: Change the autogenerated stub
       static::addGlobalScope(new AdminScope);
   }
   static $variable='';
    public function incomes(){
        return $this->hasMany(Income::class,'user_id',$this->primaryKey);
    }
    public static function detail_incomes(){
       return self::hasManyThrough(Detail_Income::class,Income::class,'user_id','income_id','user_id','income_id');
    }


}
