<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\ApiController;
use App\Http\Controllers\Controller;
use App\Models\Admin;
use App\Models\Category;
use Illuminate\Http\Request;

class CategoryController extends ApiController
{

    public function __construct()
    {
        $this->name ='category';
        $this->model = new Category();
        $this->namePlural = 'categories';
        $this->rules=['category_name'=>'required|string'];



    }
    public function index(){
        return $this->_showAll();
    }
    public function show($id){
        return $this->_showOne($id);
    }
    public function update(Request $request, $id)
    {

        return $this->_update($request,$id);
        // TODO: Change the autogenerated stub
    }
    public function store(Request $request){

        return $this->_store($request);
    }

    public function destroy($id)
    {
        return $this->_delete($id);
    }

}
